import logging
import random
import threading
import time
from typing import Optional, List, Dict, Any, Union, Tuple

from google import genai
from google.genai import types

from src.config import Config
from src.models import LLMConfig

logger = logging.getLogger(__name__)

LLM_AVAILABLE = True


class RateLimitExhaustedError(RuntimeError):
    """
    Raised when the primary model AND every fallback model all fail
    exclusively due to 429 / RESOURCE_EXHAUSTED rate-limiting.

    Callers can catch this specifically to suppress downstream work
    (e.g. image generation) that only makes sense when an article was
    successfully generated by the LLM.
    """


# Ordered fallback chain used when the primary model hits a rate limit.
# Preference: same-family lite variant first (higher quota), then Pro variant.
# Update this list after running: python scratch/test_model_availability.py
RATE_LIMIT_FALLBACK_MODELS: list = [
    "gemini-2.5-flash-lite",   # Same 2.5 family — higher burst quota
    "gemini-2.5-pro",          # Pro variant — higher quality fallback
]

# Thread-safe/module-level cooldown tracking for rate-limited models.
# Key: model_name, Value: timestamp (float) when cooldown expires.
_MODEL_COOLDOWNS: dict = {}
COOLDOWN_DURATION_SEC = 60.0


class TokenBucketLimiter:
    """
    A thread-safe, blocking token bucket rate limiter.

    This limiter refuels lazily during access and forces caller threads
    to block (sleep) when capacity is exhausted.
    """

    def __init__(self, capacity: float, fill_rate: float) -> None:
        """
        Initialize the token bucket limiter.

        Args:
            capacity: The maximum capacity of the bucket (burst limit).
            fill_rate: The rate of token generation per second.
        """
        self.capacity: float = capacity
        self.fill_rate: float = fill_rate
        self.tokens: float = float(capacity)
        self.last_refill: float = time.monotonic()
        self.lock: threading.Lock = threading.Lock()

    def acquire(self, amount: float = 1.0) -> None:
        """
        Acquire a token from the bucket. Blocks if capacity is exceeded.

        Args:
            amount: The number of tokens to acquire.
        """
        while True:
            with self.lock:
                now: float = time.monotonic()
                elapsed: float = now - self.last_refill
                if elapsed > 0.0:
                    self.tokens = min(self.capacity, self.tokens + elapsed * self.fill_rate)
                    self.last_refill = now

                if self.tokens >= amount:
                    self.tokens -= amount
                    return

                needed: float = amount - self.tokens
                sleep_time: float = needed / self.fill_rate

            time.sleep(sleep_time)


_MODEL_LIMITERS: Dict[str, TokenBucketLimiter] = {}
_LIMITER_LOCK: threading.Lock = threading.Lock()


def get_limiter_for_model(model_name: str) -> Optional[TokenBucketLimiter]:
    """
    Get or dynamically create a rate limiter for a specific model.

    Args:
        model_name: The name of the model to get a rate limiter for.

    Returns:
        The TokenBucketLimiter instance, or None if rate limiting is disabled.
    """
    if not Config.RATE_LIMIT_ENABLED:
        return None

    clean_model: str = model_name.replace("gemini/", "", 1).lower()

    with _LIMITER_LOCK:
        if clean_model in _MODEL_LIMITERS:
            return _MODEL_LIMITERS[clean_model]

        # Select appropriate limit based on model type
        if "pro" in clean_model:
            rpm: float = Config.GEMINI_RPM_LIMIT_PRO
            # Pro models: capacity 1.0 to prevent concurrent bursts exceeding 2 RPM
            limiter = TokenBucketLimiter(capacity=1.0, fill_rate=rpm / 60.0)
            logger.info("[RATE_LIMIT_INIT] Created Pro limiter for %s with %.1f RPM", clean_model, rpm)
        elif "flash" in clean_model or "lite" in clean_model:
            rpm: float = Config.GEMINI_RPM_LIMIT_FLASH
            # Flash models: capacity 2.0 to allow small transient bursts
            limiter = TokenBucketLimiter(capacity=2.0, fill_rate=rpm / 60.0)
            logger.info("[RATE_LIMIT_INIT] Created Flash limiter for %s with %.1f RPM", clean_model, rpm)
        else:
            rpm: float = Config.GEMINI_RPM_LIMIT_DEFAULT
            limiter = TokenBucketLimiter(capacity=2.0, fill_rate=rpm / 60.0)
            logger.info("[RATE_LIMIT_INIT] Created default limiter for %s with %.1f RPM", clean_model, rpm)

        _MODEL_LIMITERS[clean_model] = limiter
        return limiter


class ClientManager:
    """Singleton manager for the GenAI Client."""

    _client: Optional[genai.Client] = None

    @classmethod
    def get_client(cls) -> genai.Client:
        """
        Lazy initialization of the GenAI Client.

        Returns:
            genai.Client: The initialized client instance.
        """
        if cls._client is None:
            try:
                if Config.USE_VERTEX_AI:
                    cls._client = genai.Client(
                        vertexai=True,
                        project=Config.GOOGLE_CLOUD_PROJECT,
                        location=Config.GOOGLE_CLOUD_LOCATION
                    )
                    logger.info(
                        "[CLIENT_INIT] Mode: Vertex AI | Project: %s | Location: %s",
                        Config.GOOGLE_CLOUD_PROJECT,
                        Config.GOOGLE_CLOUD_LOCATION
                    )
                else:
                    if Config.GOOGLE_AI_STUDIO_API_KEY:
                        cls._client = genai.Client(api_key=Config.GOOGLE_AI_STUDIO_API_KEY)
                        logger.info("[CLIENT_INIT] Mode: API Key")
                    else:
                        # Auto-detect local ADC credentials to use the Gemini API (generativelanguage.googleapis.com)
                        cls._client = genai.Client()
                        logger.info("[CLIENT_INIT] Mode: Application Default Credentials (ADC) for Gemini API")
            except Exception as ex:
                logger.error("[CLIENT_INIT_FAILED] Error: %s", ex)
                raise
        return cls._client


def get_fallback_models(primary_model: str, custom_fallbacks: Optional[List[str]]) -> List[str]:
    """
    Get the fallback models list based on primary model and config fallbacks.

    Args:
        primary_model: The name of the primary model.
        custom_fallbacks: Optional user-provided fallback models list.

    Returns:
        List of fallback model names.
    """
    models: List[str] = [primary_model]
    if not custom_fallbacks:
        for model in RATE_LIMIT_FALLBACK_MODELS:
            clean_m = model.replace("gemini/", "", 1)
            if clean_m != primary_model:
                models.append(clean_m)
    else:
        for model in custom_fallbacks:
            clean_m = model.replace("gemini/", "", 1)
            if clean_m not in models:
                models.append(clean_m)
    return models


def _log_model_switch(
    attempt_model: str,
    filtered_models: List[str],
    task_name: str,
    is_429: bool,
    ex: Exception
) -> None:
    """Helper to log model switching or exhaustion details."""
    next_idx: int = filtered_models.index(attempt_model) + 1
    if next_idx < len(filtered_models):
        next_model: str = filtered_models[next_idx]
        if is_429:
            logger.info(
                "[MODEL_SWITCH] Model %s rate-limit retries exhausted. "
                "Switching to next fallback model: %s. Task: %s",
                attempt_model,
                next_model,
                task_name
            )
        else:
            logger.info(
                "[MODEL_SWITCH] Model %s failed with non-rate-limit error: %s. "
                "Switching to next fallback model: %s. Task: %s",
                attempt_model,
                ex,
                next_model,
                task_name
            )
    else:
        if is_429:
            logger.warning(
                "[GENERATION_429_EXHAUSTED] Model %s rate-limit retries exhausted. "
                "No more fallback models available! Task: %s",
                attempt_model,
                task_name
            )
        else:
            logger.warning(
                "[GENERATION_FAILED] Model %s failed. "
                "No more fallback models available! Task: %s | Error: %s",
                attempt_model,
                task_name,
                ex
            )


def _log_generation_attempt(attempt_model: str, primary_model: str, task_name: str, retry: int) -> None:
    """Log the generation attempt details."""
    label = "GENERATION_ATTEMPT"
    if attempt_model != primary_model:
        label = "FALLBACK_ATTEMPT"
    logger.info(
        "[%s] Task: %s | Model: %s (attempt %d/%d)",
        label,
        task_name,
        attempt_model,
        retry + 1,
        Config.GEMINI_MAX_RETRIES + 1
    )


def _apply_circuit_breaker(
    primary_model: str,
    models_to_try: List[str],
    task_name: str
) -> List[str]:
    """Apply circuit breaker cooldown logic and return candidate models."""
    filtered = [
        m for m in models_to_try
        if m not in {k for k, v in _MODEL_COOLDOWNS.items() if time.time() < v}
    ]
    if not filtered:
        return models_to_try
    if filtered[0] != primary_model:
        logger.info(
            "[CIRCUIT_BREAKER] Primary model %s is cooling down due to recent 429 rate limits. "
            "Bypassing directly to fallback: %s. Task: %s",
            primary_model,
            filtered[0],
            task_name
        )
    return filtered


def call_llm(
    prompt: str,
    config: Optional[LLMConfig] = None
) -> Union[str, Tuple[str, Dict[str, Any]]]:
    """
    Call the Gemini model via the Google Gen AI SDK with fallback support.

    Args:
        prompt: The text prompt to send to the model.
        config: Configuration parameters for the generation.

    Returns:
        Generated content as a string, or a tuple of (content, usage_data) if requested.
    """
    if config is None:
        config = LLMConfig(model_name=Config.MODEL_NAME)

    client = ClientManager.get_client()
    primary_model = config.model_name.replace("gemini/", "", 1)
    models_to_try = get_fallback_models(primary_model, config.fallback_models)
    filtered_models = _apply_circuit_breaker(primary_model, models_to_try, config.task_name)

    last_error = None
    all_failures_are_rate_limits = True

    for attempt_model in filtered_models:
        limiter = get_limiter_for_model(attempt_model)

        for retry_attempt in range(Config.GEMINI_MAX_RETRIES + 1):
            try:
                if limiter:
                    limiter.acquire()

                _log_generation_attempt(attempt_model, primary_model, config.task_name, retry_attempt)

                response = client.models.generate_content(
                    model=attempt_model,
                    contents=prompt,
                    config=types.GenerateContentConfig(
                        temperature=config.temperature,
                        max_output_tokens=config.max_tokens,
                        presence_penalty=config.presence_penalty,
                        frequency_penalty=config.frequency_penalty
                    )
                )

                if not response.text:
                    raise ValueError(f"Empty response from model {attempt_model}")

                logger.info(
                    "[GENERATION_SUCCESS] Task: %s | Model: %s",
                    config.task_name,
                    attempt_model
                )

                if config.include_usage:
                    return response.text, _extract_usage_data(response, attempt_model)

                return response.text

            except (RuntimeError, ValueError, TypeError, OSError, AttributeError, LookupError) as ex:
                last_error = ex
                is_429 = any(k in str(ex).upper() for k in ("429", "RESOURCE_EXHAUSTED", "TOO MANY REQUESTS"))

                if not is_429:
                    all_failures_are_rate_limits = False

                if is_429 and retry_attempt < Config.GEMINI_MAX_RETRIES:
                    logger.warning(
                        "[GENERATION_429] Model %s hit rate limit (429/RESOURCE_EXHAUSTED). "
                        "Retrying with exponential backoff... Error: %s",
                        attempt_model,
                        ex
                    )
                    time.sleep((2.0 ** retry_attempt) + random.uniform(0.5, 1.5))
                    continue

                if is_429:
                    _MODEL_COOLDOWNS[attempt_model] = time.time() + COOLDOWN_DURATION_SEC

                _log_model_switch(attempt_model, filtered_models, config.task_name, is_429, ex)
                break

    if all_failures_are_rate_limits:
        fallbacks_tried = filtered_models[1:] if len(filtered_models) > 1 else 'None'
        raise RateLimitExhaustedError(
            f"[RATE_LIMIT_EXHAUSTED] All models rate-limited for task '{config.task_name}'. "
            f"Primary: {primary_model}. Fallbacks tried: {fallbacks_tried}. "
            f"Last error: {last_error}"
        )
    raise RuntimeError(
        f"[GENERATION_FAILED] All models failed for task '{config.task_name}'. "
        f"Last error: {last_error}"
    )




def _extract_usage_data(response: Any, model: str) -> Dict[str, Any]:
    """Extract usage metadata and calculate cost from the SDK response."""
    usage_data = {
        "prompt_tokens": 0,
        "completion_tokens": 0,
        "total_tokens": 0,
        "cost": 0.0
    }

    if hasattr(response, 'usage_metadata') and response.usage_metadata:
        p_tokens = response.usage_metadata.prompt_token_count
        c_tokens = response.usage_metadata.candidates_token_count
        t_tokens = response.usage_metadata.total_token_count

        usage_data.update({
            "prompt_tokens": p_tokens,
            "completion_tokens": c_tokens,
            "total_tokens": t_tokens,
            "cost": _calculate_cost(model, p_tokens, c_tokens)
        })

    return usage_data


def _calculate_cost(model: str, prompt_tokens: int, completion_tokens: int) -> float:
    """
    Calculate approximate cost for Google Gemini models.
    Pricing per 1M tokens.
    """
    pricing = {
        "gemini-3-flash": {"input": 0.50, "output": 3.00},
        "gemini-3-pro": {"input": 3.00, "output": 15.00},
        "gemini-2.5-flash": {"input": 0.10, "output": 0.40},
        "gemini-2.5-flash-lite": {"input": 0.10, "output": 0.40},
        "gemini-2.0-flash": {"input": 0.075, "output": 0.30},
        "gemini-2.0-pro": {"input": 1.25, "output": 5.00},
        "gemini-1.5-pro": {"input": 1.25, "output": 5.00},
        "gemini-1.5-flash": {"input": 0.075, "output": 0.30},
    }

    model_pricing = None
    # Match the model name against the pricing table
    for key in sorted(pricing.keys(), key=len, reverse=True):
        if key in model.lower():
            model_pricing = pricing[key]
            break

    if not model_pricing:
        return 0.0

    input_cost = (prompt_tokens / 1_000_000) * model_pricing["input"]
    output_cost = (completion_tokens / 1_000_000) * model_pricing["output"]

    return input_cost + output_cost


def get_available_models() -> List[str]:
    """Returns a list of supported Gemini models."""
    return [
        "gemini-2.5-flash",
        "gemini-2.5-flash-lite",
        "gemini-2.5-pro",
    ]
